//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC2Beta2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HAC2Beta2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap HACGlobal_CloseButton {
            get {
                object obj = ResourceManager.GetObject("HACGlobal_CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACLogin_ConnectBTN {
            get {
                object obj = ResourceManager.GetObject("HACLogin_ConnectBTN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACLogin_FormBG {
            get {
                object obj = ResourceManager.GetObject("HACLogin_FormBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACLogin_Logo {
            get {
                object obj = ResourceManager.GetObject("HACLogin_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACLogin_TxtBoxBG {
            get {
                object obj = ResourceManager.GetObject("HACLogin_TxtBoxBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_FormBG {
            get {
                object obj = ResourceManager.GetObject("HACMain_FormBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_GametypeCTF {
            get {
                object obj = ResourceManager.GetObject("HACMain_GametypeCTF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_GametypeKing {
            get {
                object obj = ResourceManager.GetObject("HACMain_GametypeKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_GametypeOddball {
            get {
                object obj = ResourceManager.GetObject("HACMain_GametypeOddball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_GametypeRace {
            get {
                object obj = ResourceManager.GetObject("HACMain_GametypeRace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_GametypeSlayer {
            get {
                object obj = ResourceManager.GetObject("HACMain_GametypeSlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapBattlecreek {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapBattlecreek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapBloodgulch {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapBloodgulch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapBoardingaction {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapBoardingaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapChillout {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapChillout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapChiron {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapChiron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapDamnation {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapDamnation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapDangercanyon {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapDangercanyon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapDeathisland {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapDeathisland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapDerelict {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapDerelict", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapGephyrophobia {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapGephyrophobia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapHangemhigh {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapHangemhigh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapIceFields {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapIceFields", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapInfinity {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapInfinity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapLongest {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapLongest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapPrisoner {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapPrisoner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapRatrace {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapRatrace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapSidewinder {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapSidewinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapTimberland {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapTimberland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MapWizard {
            get {
                object obj = ResourceManager.GetObject("HACMain_MapWizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuChat {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuChat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuChatH {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuChatH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuChatI {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuChatI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuHome {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuHomeH {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuHomeH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuHomeI {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuHomeI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuServers {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuServers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuServersH {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuServersH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACMain_MenuServersI {
            get {
                object obj = ResourceManager.GetObject("HACMain_MenuServersI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACValidate_BackProg {
            get {
                object obj = ResourceManager.GetObject("HACValidate_BackProg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACValidate_FormBG {
            get {
                object obj = ResourceManager.GetObject("HACValidate_FormBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HACValidate_FrontProg {
            get {
                object obj = ResourceManager.GetObject("HACValidate_FrontProg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MasterChiefIcon {
            get {
                object obj = ResourceManager.GetObject("MasterChiefIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
